version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: cs_inventory_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cs_inventory
      MYSQL_USER: csuser
      MYSQL_PASSWORD: cspass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ucsuser", "-pcspass"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cs_inventory_backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cs_inventory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: csuser
      SPRING_DATASOURCE_PASSWORD: cspass
      # 可选 JVM 参数示例：-Xms256m -Xmx512m
      JAVA_OPTS: -XX:+UseContainerSupport
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "9090:9090"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cs_inventory_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
